services:
  nginx:
    container_name: nginx_schedule
    restart: always
    image: byjg/nginx-extras:latest
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
      - ./app/logs:/root/logs
    depends_on:
      - schedule_api

  schedule_api:
    container_name: schedule_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000

    volumes:
      - ./app/logs:/root/logs

    command: >
      sh -c "uvicorn main:app --reload -- host 0.0.0.0 -port 80 --proxy-headers &&
            tail -F anything"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12.0
    ports:
      - 5432:5432
    environment:
      DB_USER=postgres
      DB_PASSWORD=3141592653589
      DB_NAME=test1
      DB_HOST=localhost

